import getters from './getters'
export default {
    namespaced: true,
    state :{
        players:[
            {
                name:'Muslera',
                formNumber:'1',
                photo:'https://cdn.gsstore.org/UPLOAD/images/customization/player/11-fernando-muslera.jpg'
            },
            {
                name:'Batuhan',
                formNumber:'12',
                photo:'https://cdn.gsstore.org/UPLOAD/images/customization/player/batuhan-senn.jpg'
            },
            {
                name:'Okan Kocuk',
                formNumber:'34',
                photo:'https://cdn.gsstore.org/UPLOAD/images/customization/player/34-Okan-Kocuk.jpg'
            },
            {
                name:'Jankat',
                formNumber:'50',
                photo:'https://cdn.gsstore.org/UPLOAD/images/customization/player/50-Jankat.jpg'
            },
            {
                name:'Duboıs',
                formNumber:'2',
                photo:'https://cdn.gsstore.org/UPLOAD/images/customization/player/2-Leo-Dubois.jpg'
            },
            {
                name:'Işık Kaan',
                formNumber:'24',
                photo: 'https://cdn.gsstore.org/UPLOAD/images/customization/player/24-Kaan-Arslann.jpg'
            },
            {
                name:'Nelsson',
                formNumber:'25',
                photo:'https://cdn.gsstore.org/UPLOAD/images/customization/player/yirmibes-nelson.jpg'
            },
            {
                name:'Emin',
                formNumber:'40',
                photo:'https://cdn.gsstore.org/UPLOAD/images/customization/player/40-Emin-Bayram.jpg'
            },
            {
                name:'Abdulkerim',
                formNumber:'42',
                photo:'https://cdn.gsstore.org/UPLOAD/images/customization/player/42-Abdulkerim.jpg'
            },
            {
                name:'Boey',
                formNumber:'93',
                photo:'https://cdn.gsstore.org/UPLOAD/form-customize/player/BOEY.jpg'
            },
            {
                name:'Ross',
                formNumber:'4',
                photo:'https://cdn.gsstore.org/UPLOAD/images/customization/player/ross.jpg'
            },
            {
                name:'Kazım Can',
                formNumber:'88',
                photo:'https://cdn.gsstore.org/UPLOAD/images/customization/player/88-Kazimcan.jpg'
            },
            {
                name:'Metehan',
                formNumber:'90',
                photo:'https://cdn.gsstore.org/UPLOAD/images/customization/player/90-Metehan.jpg'
            },
            {
                name:'Mıdtsjö',
                formNumber:'6',
                photo:'https://cdn.gsstore.org/UPLOAD/images/customization/player/6-Fredrik.jpg'
            },
            {
                name:'B.Kutlu',
                formNumber:'22',
                photo:'https://cdn.gsstore.org/UPLOAD/form-customize/player/yirmiki-berkan.jpg'
            },
            {
                name:'Torreıra',
                formNumber:'5',
                photo:'https://cdn.gsstore.org/UPLOAD/images/customization/player/Lucas-Torreira-1.jpg'
            },
            {
                name:'Barış',
                formNumber:'53',
                photo:'https://cdn.gsstore.org/UPLOAD/images/customization/player/baris-alper-53.jpg'
            },
            {
                name:'Hamza',
                formNumber:'81',
                photo:'https://cdn.gsstore.org/UPLOAD/images/customization/player/81-hamza-yigit.jpg'
            },
            {
                name:'Özgür Baran',
                formNumber:'63',
                photo:'https://cdn.gsstore.org/UPLOAD/images/customization/player/63-baran-aksaka.jpg'
            },
            {
                name:'Mata',
                formNumber:'64',
                photo:'https://cdn.gsstore.org/UPLOAD/images/customization/player/mata.jpg'
            },
            {
                name:'Sergıo',
                formNumber:'27',
                photo:'https://cdn.gsstore.org/UPLOAD/images/customization/player/27-Sergio-Oliveira.jpg'
            },
            {
                name:'Aktürkoğlu',
                formNumber:'7',
                photo:'https://cdn.gsstore.org/UPLOAD/images/customization/player/yedi-kerem-akturkoglu.jpg'
            },
            {
                name:'Demir',
                formNumber:'30',
                photo:'https://cdn.gsstore.org/UPLOAD/images/customization/player/yusuf.jpg'
            },
            {
                name:'Gomıs',
                formNumber:'18',
                photo:'https://cdn.gsstore.org/UPLOAD/images/customization/1818-bafetimbi-gomis.jpg'
            },
            {
                name:'Yunus',
                formNumber:'11',
                photo:'https://cdn.gsstore.org/UPLOAD/images/customization/player/11-yunus.jpg'
            },
            {
                name:'Mertens',
                formNumber:'10',
                photo:'https://cdn.gsstore.org/UPLOAD/images/customization/player/Dries-Mertens1.jpg'
            },
            {
                name:'IrzDüsmani İcardi',
                formNumber:'99',
                photo:'https://cdn.gsstore.org/UPLOAD/images/customization/player/icardi.jpg'
            },
            {
                name:'Rashıca',
                formNumber:'26',
                photo:'https://cdn.gsstore.org/UPLOAD/images/customization/player/rashica.jpg'
            }
        ]
    },
    getters
}